[package]
name = "lark-unify"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
lark-collections = { path = "../lark-collections" }
lark-debug-with = { path = "../lark-debug-with" }
