[package]
name = "lark-language-server"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
languageserver-types = "0.51.0"

lark-task-manager = { path = "../lark-task-manager" }