[package]
name = "intern"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
indices = { path = "../indices" }
map = { path = "../map" }
parking_lot = "0.6.4"