[package]
name = "lark-query-system"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
codespan = "0.1.3"
debug = { path = "../debug" }
intern = { path = "../intern" }
hir = { path = "../hir" }
languageserver-types = "0.51.0"
lark-entity = { path = "../lark-entity" }
lark-task-manager = { path = "../lark-task-manager" }
map = { path = "../map" }
parking_lot = "0.6.4"
parser = { path = "../parser" }
salsa = "0.6.2"
ty = { path = "../ty" }
type-check = { path = "../type-check" }
url = "1.7"