[package]
name = "lark-query-system"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
codespan = "0.2.0"
debug = { path = "../debug" }
intern = { path = "../intern" }
languageserver-types = "0.51.0"
lark-entity = { path = "../lark-entity" }
lark-error = { path = "../lark-error" }
lark-hir = { path = "../lark-hir" }
lark-mir2 = { path = "../lark-mir2" }
lark-parser = { path = "../lark-parser" }
lark-string = { path = "../lark-string" }
lark-task-manager = { path = "../lark-task-manager" }
lark-ty = { path = "../lark-ty" }
lark-type-check = { path = "../lark-type-check" }
log = "0.4.5"
map = { path = "../map" }
parking_lot = "0.6.4"
parser = { path = "../parser" }
salsa = "0.8"
url = "1.7"
